### ISSUE TITLE
fbcmd R.I.P

### ISSUE THREAD

**Issue by heriipurnama** [agusmakmun/Status-Facebook-Menggunakan-Python#2]
bukanya fbcmd projek yang sudah tidak aktif ya mas...kemaren saya membaca pada 
di [https://github.com/dtompkins/fbcmd/issues/17](url)
dan ketika saya mengakses ke alamat
$ fbcmd go auth dan $ fbcmd go access
![rip](https://cloud.githubusercontent.com/assets/10396992/13381042/e1fe3a46-de83-11e5-8e4d-959f10033347.png)

selalu ditampilkan halaman kosong...
halamannya seperti ini
http://dtompkins.com/fbcmd/
![rip fbcmd](https://cloud.githubusercontent.com/assets/10396992/13381027/8903861c-de83-11e5-8345-da6c37f783c0.png)

**Comment by agusmakmun** [comment]
Oh iya mas, maaf saya lupa update.. di tool ini: https://github.com/agusmakmun/Python-Bot-Facebook-R.I.P, sudh saya update, cuman yang ini belum. Terimakasih sudah mengingatkan.

**Comment by heriipurnama** [comment]
iya mas . . .sama-sama. . ..
